# Generated by Django 4.0.10 on 2023-05-12 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('converted', models.BooleanField(default=False)),
                ('converted_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campaigns.lead')),
            ],
        ),
    ]
