# Generated by Django 4.2.1 on 2023-05-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campaigns', '0003_campaignlandingpage_subscriber'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together=set(),
        ),
    ]
